// COMMON
const WHITE = '#FFFFFF';
const BLACK = '#000000';
const TRANSPARENT = 'transparent';

const PRIMARY = '#8BA88E'

const WHITE_BG = '#E5E5E5'
const LIME_GREEN = '#8BA88E'
const LABEL_LIMED = '#3B4E51'
const INPUT_BORDER = '#D0D5DD'
const GRAY_PLACEHOLDER = 'rgba(0, 0, 0, 0.5)'
const ERROR = '#f04438'
const ERROR_CARD_BG = '#f8d7da'
const ERROR_CARD_TEXT = '#842029'
const ERROR_INPUT_BORDER = '#FDA29B'
const TOGGLE_BTN_SELECTED_TEXT = '#F5F6F4';
const TOGGLE_BTN_UNSELECTED_TEXT = '#344054';
const ERROR_BORDER = '#FDA29B';
const TOOLTIP_BG = '#3A4E51';
const BOTTOM_TAB_FOCUSED = '#536E56'
const HEADING_TEXT_BLACK = '#353535'
const CARD_TITLE = '#484848'
const BOOK_APPOINTMENT_BG = '#E7F0E7'
const BOOK_APPOINTMENT_BORDER = '#E2E2E2'
const LEFT_BORDER_PINK = '#AD5171'
const DOCTOR_HEART_BG = '#ACC0AE'
const QUOTE_BY = '#B4B8B1'
const BLUE = '#30A9CF'
const SEARCH_BAR_BORDER = '#DEDEDE'
const USER_HELP_TEXT = '#536F57'
const HEADER_BG = '#3F5455'
const SEARCH_BORDER = '#CACACA'
const SEARCH_BG = '#FDFFFB'
const AUTH_BG = '#F5F6F4'
const OTP_LABEL_GRAY = '#344054'
const DARK_GREEN = '#3F5455'
const DOC_GREEN = '#039351'
const LAB_HEADER_BTN = '#8BA88E'
const LAB_HEADER_BTN_BG = '#F4FCF5'
const LAB_ADD_NEW_DOC = '#8BA78E'
const ORANGE = '#E79720'
const DATE_GRAY = '#8D8D8D'
const BLUE_BTN_TEXT = '#309DCC'
const SWITCH_BORDER = '#DFDFDF'
const DOC_BORDER = '#C4C4C4'
const SPLASH_BG = '#EBF2EC'
const LIGHTGREY = "#ece5e5"
const INFOTEXT = "black"
const MEDCOLLECTION = "#5A786F"

const STATUS_BAR = {
    PROFILE: '#F5F6F4'
}

export default {
    WHITE,
    BLACK,
    TRANSPARENT,
    PRIMARY,
    WHITE_BG,
    LIME_GREEN,
    LABEL_LIMED,
    INPUT_BORDER,
    GRAY_PLACEHOLDER,
    ERROR,
    ERROR_CARD_BG,
    ERROR_CARD_TEXT,
    ERROR_BORDER,
    ERROR_INPUT_BORDER,
    TOGGLE_BTN_SELECTED_TEXT,
    TOGGLE_BTN_UNSELECTED_TEXT,
    ERROR_BORDER,
    TOOLTIP_BG,
    BOTTOM_TAB_FOCUSED,
    HEADING_TEXT_BLACK,
    CARD_TITLE,
    BOOK_APPOINTMENT_BG,
    BOOK_APPOINTMENT_BORDER,
    LEFT_BORDER_PINK,
    DOCTOR_HEART_BG,
    QUOTE_BY,
    BLUE,
    SEARCH_BAR_BORDER,
    USER_HELP_TEXT,
    HEADER_BG,
    SEARCH_BORDER,
    SEARCH_BG,
    AUTH_BG,
    OTP_LABEL_GRAY,
    DARK_GREEN,
    STATUS_BAR,
    LAB_HEADER_BTN,
    LAB_HEADER_BTN_BG,
    LAB_ADD_NEW_DOC,
    ORANGE,
    DATE_GRAY,
    DOC_GREEN,
    BLUE_BTN_TEXT,
    SWITCH_BORDER,
    DOC_BORDER,
    SPLASH_BG,
    LIGHTGREY,
    INFOTEXT,
    MEDCOLLECTION
}
